[package]
name = "core-subscription"
version = "0.0.8"
edition = "2021"

[dependencies]
serde = "1.0.188"
serde_json = "1.0.105"
tokio = { version = "1.32.0", features = ["full"] }
tokio-util = "0.7.8"
tracing = { version = "0.1.37", features = ["log"] }
tracing-subscriber = { version = "0.3.1", default-features = false, features = ["fmt"] }
lambda_runtime = "0.8.2"
aws_lambda_events = "0.12.1"
aws-config = { version = "1.0.1", features = ["behavior-version-latest"] }
aws-sdk-athena = "1.1.0"

[dev-dependencies]
tokio-test = "0.4.3"
tracing-test = "0.2.4"
chrono = "0.4.30"
