name: Release

on:
  pull_request:
    branches:
      - main
#    types:
#      - closed

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  role:
    #    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: SetVars
        run: |
          sed -i 's/${AWS::AccountId}/${{ secrets.AWS_ACCOUNT_ID }}/' infra/role/template.yml

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubDeployBase
          role-session-name: ${{ vars.SESSION_NAME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: SAM Role
        run: |
          cd infra/role
          sam build
          sam package
          sam deploy

  deploy:
    runs-on: macos-latest
    environment: Production
    needs: Role
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: cargo-lambda
        run: |
          brew tap cargo-lambda/cargo-lambda
          brew install cargo-lambda

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubDeployCoreSubscription
          role-session-name: ${{ vars.SESSION_NAME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: SAM Publish
        run: |
          cd infra/step
          sam build
          sam package
          sam publish

      - name: Get Version
        id: version
        run: |
          export CURRENT_VERSION=$(grep -m 1 'version = "' Cargo.toml | awk -F '"' '{print $2}')
          echo "current=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.version.outputs.current }}
