name: Report
on:
  workflow_run:
    workflows: ['Tests']
    types:
      - completed
jobs:
  junit:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results
          name: JUnit Tests
          path: '*.xml'
          reporter: java-junit
